# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

[uwsgi]
socket = 0.0.0.0:5001
stats = 0.0.0.0:9001
module = invenio_app.wsgi_rest:application
master = true
die-on-term = true
processes = 2
threads = 2
mount = /api=invenio_app.wsgi_rest:application
manage-script-name = true
single-interpreter = true

ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true
