# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

[uwsgi]
socket = 0.0.0.0:5000
stats = 0.0.0.0:9000
module = invenio_app.wsgi_ui:application
master = true
die-on-term = true
processes = 2
threads = 2
single-interpreter = true

ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true
