# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

# Extraction from Python source files
[python: **.py]
encoding = utf-8
[python: **/manual_translations.txt]
encoding = utf-8

# Extraction from Jinja2 templates
[jinja2: **/templates/**.html]
encoding = utf-8
extensions = jinja2.ext.do

# Extraction from JavaScript files
[javascript: **.js]
encoding = utf-8
extract_messages = $._, jQuery._

# Extraction from json files (schema)
[json: **.json]
keys_to_translate = ['^title$', '^label$', '^description$', '^placeholder$', '^.*Message$']
