# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM python:3.14-slim-bookworm

# require debian packages
RUN apt-get upgrade -y && apt-get update -y
RUN apt-get install --no-install-recommends -y git vim-tiny curl gcc g++ pkg-config gnupg libc6-dev libxmlsec1-openssl xpdf xpdf-utils ghostscript imagemagick rsync && rm -rf /var/lib/apt/lists/*
RUN sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml
RUN pip install --upgrade wheel pip uv

# Install Node
RUN apt-get update && apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_24.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt-get install nodejs -y && rm -rf /var/lib/apt/lists/*

# Env variables
ENV WORKING_DIR=/invenio
ENV INVENIO_INSTANCE_PATH=${WORKING_DIR}/var/instance

# Create directories
RUN mkdir -p ${INVENIO_INSTANCE_PATH}
RUN mkdir -p ${WORKING_DIR}/src
RUN mkdir -p ${WORKING_DIR}/instance

# copy everything inside /src
COPY ./ ${WORKING_DIR}/src
WORKDIR ${WORKING_DIR}/src

# copy uwsgi config files
COPY ./docker/uwsgi/ ${INVENIO_INSTANCE_PATH}

# Set folder permissions
ENV INVENIO_USER_ID=1000
RUN useradd invenio --uid ${INVENIO_USER_ID}  --home ${WORKING_DIR} && \
    chown -R invenio:invenio ${WORKING_DIR} && \
    chmod -R go+w ${WORKING_DIR}

USER 1000
