#!/usr/bin/env bash
# Swiss Open Access Repository
# Copyright (C) 2021-2025 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

NC='\033[0m'                    # Default color
INFO_COLOR='\033[1;97;44m'      # Bold + white + blue background
SUCCESS_COLOR='\033[1;97;42m'   # Bold + white + green background
ERROR_COLOR='\033[1;97;41m'     # Bold + white + red background

PROGRAM=`basename $0`

source $(dirname "$0")/functions

set -e

# MESSAGES
msg() {
  echo -e "${1}" 1>&2
}
# Display a colored message
# More info: https://misc.flogisoft.com/bash/tip_colors_and_formatting
# $1: choosen color
# $2: title
# $3: the message
colored_msg() {
  msg "${1}[${2}]: ${3}${NC}"
}

info_msg() {
  colored_msg "${INFO_COLOR}" "INFO" "${1}"
}

error_msg() {
  colored_msg "${ERROR_COLOR}" "ERROR" "${1}"
}

error_msg+exit() {
    error_msg "${1}" && exit 1
}

success_msg() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}"
}

# Displays program name
msg "PROGRAM: ${PROGRAM}"

flags=()
deploy=false
cmd="uv sync --frozen"
ci=false
tgz_file=""

# uv is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  error_msg "Launch this script via uv command: uv run ${PROGRAM}"
  exit 1
fi

# Check arguments and options
while test $# -gt 0; do
    case "$1" in
        -t|--tgz_package)
          tgz_file=$2
          if [[ ! -f "${tgz_file}" ]]
          then
            error_msg+exit "package tgz file does not exist: ${tgz_file}"
          fi
          shift;;
        -c|--ci)
          # We are probably running webaction, check for env variables
          ci=true ;;
        --deploy)
            deploy=true
            ;;
        *) error_msg "Option $1 not recognized" ;;
    esac
    shift
done


title "Bootstrap script"

if $deploy ; then
  if ! $ci ; then
    flags=("--no-group dev --group prod")
  fi
else
  if $ci ; then
    cmd="uv sync --upgrade"
  fi
fi

# BOOTSTRAP START
# install the application and all the dependencies
flag="${flags[@]}"
info_msg "Install with command: ${cmd} ${flag}"
${cmd} ${flags[@]}

# Collect static files
info_msg "Collect static files"
invenio collect -v

# Store folder path
assets_folder=$(invenio shell --no-term-title -c "print(app.config.get('WEBPACKEXT_PROJECT_BUILDDIR'))")
static_folder=$(invenio shell --no-term-title -c "print('static_folder:%s' % app.static_folder)"|grep static_folder| cut -d: -f2-)

info_msg "Install assets"

# Remove installed RERO packages (in case they was installed with pack)
rm -rf ${static_folder}/node_modules

# Build webpack assets
# TODO: remove CI when the following issue is solved:
# https://github.com/inveniosoftware/invenio-assets/issues/162
# on the patch-module the option --error-on-fail is switched on by default on CI
CI="" invenio webpack buildall


# install sonar-ui
info_msg "Install static folder npm dependencies in: ${static_folder}"
if [[ -f "${tgz_file}" ]]
then
  info_msg "Install SONAR-UI from tgz: ${tgz_file}"
  npm install --no-save --only=prod --no-fund --no-audit  "${tgz_file}" --prefix "${static_folder}"
else
  npm install --no-save --only=prod --no-fund --no-audit  @rero/sonar-ui@19.0.3 --prefix "${static_folder}"
fi


# Compile translations catalogs
info_msg "Compile translations catalogs"
uv run pybabel compile -d sonar/translations

success_msg "\nBootstrap finished successfully"
