#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

source $(dirname "$0")/functions

set -e

title "Exporting data for HEG"

cd $(dirname "$0")/..

section "Harvest and export records from BORIS" "info"
uv run invenio oaiharvester harvest -a action=export -n boris -q

section "Harvest and export records from Archive ouverte UNIGE" "info"
uv run invenio oaiharvester harvest -a action=export -n archive_ouverte_unige -q
