#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

function color {
    type=$1
    if [ -f $type ]; then
        type="normal"
    fi

    # Choose color
    case $1 in
        success)
            color=2
            ;;
        error)
            color=1
            ;;
        warning)
            color=214
            ;;
        info)
            color=6
            ;;
        *)
            color=7
            ;;
    esac
}

function message {
    color $2

    # Apply color
    tput setaf $color

    # Display text
    echo -e "$(tput setaf $color)$1$(tput sgr0)"
}

function title {
    color $2
    echo -e "$(tput setaf $color)\n===================================\n$1\n===================================$(tput sgr0)"
}

function section {
    color $2
    echo -e "$(tput setaf 0; tput setab $color)\n $1 $(tput sgr0)"
}

token_create() {
  if [ -z ${3} ]
  then
      invenio utils token-create -n ${1} -u ${2}
  else
      invenio utils token-create -n ${1} -u ${2} -t ${3}
  fi
}

add_exceptions() {
  pip_audit_exceptions="$pip_audit_exceptions --ignore-vuln $1"""
}
