#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

source $(dirname "$0")/functions

set -e

# uv is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  message "Launch this script via uv command: uv run ${PROGRAM}" "error"
  exit 1
fi

title "Installation of SONAR UI library"

tarball=$1

# Store folder path
assets_folder=$(invenio shell --no-term-title -c "print(app.config.get('WEBPACKEXT_PROJECT_BUILDDIR'))")
static_folder=$(invenio shell --no-term-title -c "print('static_folder:%s' % app.static_folder)"|grep static_folder| cut -d: -f2-)

# Remove installed package
section "Remove installed packages" "info"
rm -rf ${assets_folder}/node_modules/@rero
message "Done" "success"

if test -z "$tarball"; then
    section "Create package.json file" "info"
    message "No tarball file provided, standard installation from package.json" "info"
    invenio webpack create
fi

# Install dependencies
section "Install dependencies" "info"
npm i $tarball --prefix $assets_folder

# Copy sonar-ui files to static folder to use it with flask-assets
section "Copy SONAR UI files to static folder" "info"
mkdir -p ${static_folder}/sonar-ui
cp -R ${assets_folder}/node_modules/@rero/sonar-ui/dist/sonar/* ${static_folder}/sonar-ui
message "Done" "success"

message "\nInstall UI finished!" "success"
