#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Swiss Open Access Repository
# Copyright (C) 2019 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source $(dirname "$0")/functions

set -e

title "Installation of SONAR UI library"

tarball=$1

# Remove installed package
section "Remove installed packages" "info"
rm -rf ${assets_folder}/node_modules/@rero
message "Done" "success"

if test -z "$tarball"; then
    section "Create package.json file" "info"
    message "No tarball file provided, standard installation from package.json" "info"
    invenio webpack create
fi

# Install dependencies
section "Install dependencies" "info"
invenio webpack install $tarball

# Store folder path
assets_folder=$(pipenv run invenio shell --no-term-title -c "print(app.config.get('WEBPACKEXT_PROJECT_BUILDDIR'))")
static_folder=$(pipenv run invenio shell --no-term-title -c "print('static_folder:%s' % app.static_folder)"|grep static_folder| cut -d: -f2-)

# Copy sonar-ui files to static folder to use it with flask-assets
section "Copy SONAR UI files to static folder" "info"
mkdir -p ${static_folder}/sonar-ui
cp -R ${assets_folder}/node_modules/@rero/sonar-ui/dist/sonar/* ${static_folder}/sonar-ui
message "Done" "success"

message "\nInstall UI finished!" "success"
