#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Swiss Open Access Repository
# Copyright (C) 2019 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source $(dirname "$0")/functions

set -e

title "Start web server and celery"

script_path=$(dirname "$0")

export FLASK_ENV=development

# Start Worker and Server
section "Start celery worker" "info"
celery --app invenio_app.celery worker --loglevel INFO --beat & pid_celery=$!
message "Done" "success"

# Start web server
section "Start web server" "info"
invenio run \
       --cert "$script_path"/../docker/nginx/test.crt \
       --key "$script_path"/../docker/nginx/test.key & pid_server=$!
message "Done" "success"

trap 'kill $pid_celery $pid_server &>/dev/null' EXIT

wait $pid_celery $pid_server
