#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

source $(dirname "$0")/functions

set -e
PORT=5000
CELERY_LOG_LEVEL="DEBUG"
worker=true

# uv is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  message "Launch this script via uv command: uv run ${PROGRAM}" "error"
  exit 1
fi

if ! options=$(getopt -o nlp: -l no-worker,loglevel,port: -- "$@")
then
  # something went wrong, getopt will put out an error message for us
  exit 1
fi

while [ $# -gt 0 ]
do
  case $1 in
    -p|--port) PORT=$2; shift;;
    -l|--loglevel)
      CELERY_LOG_LEVEL=$2
      shift ;;
    -n|--no-worker)
      worker=false ;;
    (--) shift; break;;
    (-*) message "$0: Unrecognized option $1" "error"; exit 1;;
  esac
  shift
done


title "Start web server and celery"

script_path=$(dirname "$0")

if [[ -z "${FLASK_DEBUG}" ]]; then
  export FLASK_DEBUG=True
fi

# Start Worker and Beat
if $worker; then
  section "Start celery worker" "info"
  celery --app sonar.celery worker --loglevel ${CELERY_LOG_LEVEL} --beat & PID_CELERY=$!
  message "Done" "success"
fi


# Start web server
section "Start web server" "info"
invenio run \
       --cert "$script_path"/../docker/nginx/test.crt \
       --key "$script_path"/../docker/nginx/test.key \
       -p $PORT & pid_server=$!

message "Done" "success"

trap 'kill $pid_celery $pid_server &>/dev/null' EXIT

wait $pid_celery $pid_server
