#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Swiss Open Access Repository
# Copyright (C) 2019 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

# Clean redis
pipenv run invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
pipenv run invenio db destroy --yes-i-know
pipenv run invenio db init create
pipenv run invenio index destroy --force --yes-i-know
pipenv run invenio index init --force
pipenv run invenio index queue init purge

# Create admin role to restrict access
pipenv run invenio roles create admin
pipenv run invenio roles create user
pipenv run invenio roles create librarian
pipenv run invenio access allow superuser-access role admin

# Create admin user and assign admin role
pipenv run invenio users create admin@sonar.ch --password 123456 --active
pipenv run invenio roles add admin@sonar.ch admin

# Import fixtures
pipenv run invenio fixtures institutions import
pipenv run invenio fixtures documents import hevs
pipenv run invenio fixtures documents import usi