#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Swiss Open Access Repository
# Copyright (C) 2021 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.

# Ignoring false positive 36759 (reporting invenio-admin v1.0.1). This can be
# removed when https://github.com/pyupio/safety-db/pull/2274 is merged and
# released.

set -e

SCRIPT_PATH=$(dirname "$0")

source ${SCRIPT_PATH}/functions

# Poetry is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  message "Launch this script via poetry command: poetry run ${PROGRAM}" "error"
  exit 1
fi

# TODO: Exceptions on safety check
# +============================+===========+==========================+==========+
# | package                    | installed | affected                 | ID       |
# +============================+===========+==========================+==========+
# | wtforms                    | 2.3.3     | <3.0.0a1                 | 42852    |
# | werkzeug                   | 1.0.1     | <2.2.3                   | 53325    |
# | werkzeug                   | 1.0.1     | <2.2.3                   | 53326    |
# | werkzeug                   | 1.0.1     | >=0,<2.1.1               | 54456    |
# | sqlalchemy                 | 1.3.24    | <2.0.0b1                 | 51668    |
# | sqlalchemy-utils           | 0.35.0    | >=0.27.0                 | 42194    |
# | setuptools                 | 57.5.0    | <65.5.1                  | 52495    |
# | sentry-sdk                 | 1.6.0     | <1.14.0                  | 53812    |
# | safety                     | 1.10.3    | <2.2.0                   | 51358    |
# | py                         | 1.11.0    | <=1.11.0                 | 51457    |
# | nbconvert                  | 6.4.5     | <6.5.1                   | 50792    |
# | flask-security             | 3.0.0     | <3.1.0                   | 45183    |
# | flask-security             | 3.0.0     | >0                       | 44501    |
# | click                      | 7.1.2     | <8.0.0                   | 47833    |
# | celery                     | 5.1.2     | <5.2.0                   | 42498    |
# | celery                     | 5.1.2     | <5.2.2                   | 43738    |
# | cryptography               | 39.0.2    | <41.0.0                  | 59062    |
# | cryptography               | 39.0.2    | <41.0.2                  | 59473    |
# | cryptography               | 39.0.2    | >=0.8, <41.0.3           | 60224    |
# | cryptography               | 39.0.2    | >=0.8, <41.0.3           | 60225    |
# | cryptography               | 39.0.2    | >=0.8,<41.0.3            | 60223    |
# | certifi                    | 2022.12.7 | >=2015.04.28,<2023.07.22 | 59956    |
# | pillow                     | 9.5.0     | <10.0.1                  | 61489    |
# +==============================================================================+
safety check -i 45183 -i 44501 -i 51668 -i 42194 -i 42852 -i 53325 -i 53326 -i 54456 -i 42498 -i 43738 -i 47833 -i 51457 -i 51358 -i 53812 -i 52495 -i 50792 -i 55261 -i 59062 -i 59473 -i 59956 -i 60223 -i 60224 -i 60225 -i 61489 -i 62019 -i 40459 -i 62451 -i 62452 -i 62556 -i 63073
pydocstyle sonar tests docs
isort --check-only --diff "${SCRIPT_PATH}/.."
autoflake -c -r --remove-all-unused-imports --ignore-init-module-imports . &> /dev/null || {
  autoflake --remove-all-unused-imports -r --ignore-init-module-imports .
  exit 1
}
sphinx-build -qnNW docs docs/_build/html
pytest

