name: CI
on: [push, pull_request, workflow_dispatch]

env:
  TERM: xterm-256color

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies: ['dev', 'deploy']
    steps:
    - uses: actions/checkout@v4

    - name: Install Libraries
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl
        sudo apt-get install -y libxml2 ghostscript imagemagick xpdf
        sudo sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Docker compose up
      run: docker compose up -d

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Set up Python
      run: uv python install 3.12

    - name: Bootstrap
      if: ${{ matrix.dependencies == 'dev' }}
      run: |
        uv run ./scripts/bootstrap --ci

    - name: Bootstrap deploy
      if: ${{ matrix.dependencies == 'deploy' }}
      run: |
        uv run ./scripts/bootstrap --ci --deploy

    - name: Run Test
      run: uv run poe run_tests

    - name: Coverage XML
      if: ${{ matrix.dependencies == 'dev' }}
      run: uv run coverage xml

    - name: Coveralls
      if: ${{ matrix.dependencies == 'dev' }}
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura